checked/fixed backup,checkout,flush actions + bugfix in wrap_rsync

diff --git a/ddm b/ddm
--- a/ddm
+++ b/ddm
@@ -457,7 +457,7 @@ wrap_rsync ()
 	ask_del=$5
 	
 	# if source is a directory, append / if needed. (needed for rsync)
-	if [ -d "$src" -a ! grep '/$' > /dev/null <<< "$src" ]
+	if [ -d "$src" ] && ! grep '/$' >/dev/null <<< "$src"
 	then
 		src="$src/"
 	fi
@@ -541,8 +541,8 @@ postbackup ()
 docheckout ()
 {
 	# all datatypes: blob buffer cache copy direct extension selection
-	# not possible: blob, direct
-	# defined for: copy selection
+	# defined for: blob, copy, direct/vfs, selection
+
 	if [ "$REPOSITORY_TYPE" == 'svn' ] && [ $DATASET_LOCAL_TYPE == "buffer" ]
 	then
 		no_action "maybe we could copy (only) the remote directories as template hierachy? Is this what you expected?"
@@ -551,7 +551,7 @@ docheckout ()
 		no_action "maybe we could copy (only) the remote directories as template hierachy? Is this what you expected?"
 	elif [ "$REPOSITORY_TYPE" == 'svn' ] && [ $DATASET_LOCAL_TYPE == "direct" ]
 	then
-		no_action
+		no_action "you want a mountpoint to the svn repository itself?  seems a bit far fetched..."
 	elif [ "$REPOSITORY_TYPE" == 'svn' ] && [ $DATASET_LOCAL_TYPE == "selection" ]
 	then
 		echo_verbose "You are checking out a selection: i assume you will delete what you don't need afterwards?"
@@ -577,7 +577,10 @@ docheckout ()
 
 docommit ()
 {
-	if [ "$REPOSITORY_TYPE" == 'svn' ]
+	# all datatypes: blob buffer cache copy direct extension selection
+	#defined for: blob, buffer/vfs (alias for flush by default), copy
+
+	if [ "$REPOSITORY_TYPE" == 'svn' ] && [ $DATASET_LOCAL_TYPE == "blob" -o $DATASET_LOCAL_TYPE == "copy" -o $DATASET_LOCAL_TYPE == "selection" ]
 	then
 		wrap_svn commit $DATASET_LOCAL_FULL -m "$MESSAGE"
 	elif [ "$REPOSITORY_TYPE" == 'vfs' ]
@@ -594,11 +597,15 @@ docommit ()
 			          gonna be hard to implement something like that..."
 		elif [ $DATASET_LOCAL_TYPE == "extension" ]
 		then
-			no_action "Since this is an extension, i woulnd't know where to send data to..."
+			no_action "Since this is an extension, i woulnd't know where to send data to...did you mean backup?"
 		elif [ $DATASET_LOCAL_TYPE == "direct" ]
 		then
 			no_action "Maybe we could umount? ( if it's a direct mount) and ask to umount if the parent is a mountpoint"
+		elif [ $DATASET_LOCAL_TYPE == "cache" ]
+		then
+			no_action "You want to commit a cache? doesn't make much sense to me..."
 		fi
+
 	fi 
 
 }
@@ -610,7 +617,8 @@ doflush ()
 	then
 		#NOTE: --remove-source-files only removes files, not directories. this can be good (directories define structure) or bad (directories function as data)
 		wrap_rsync '-avu --remove-source-files' '**.ddm' "$DATASET_LOCAL_FULL/" "$REPOSITORY_FULL" 0
-		#TODO: count/check unsuccessfully sent files
+		failures=`find $DATASET_LOCAL_FULL -type f | grep -v "$DATASET_LOCAL_FULL/.ddm" | wc -l`
+		echo "Warning: still $failures un(successfully) flushed files in the buffer" >&2
 		echo "Successfully transfered files deleted. Directories are kept; you must delete them yourself if you don't need them anymore"
 	elif [ $DATASET_LOCAL_TYPE == "cache" ]
 	then
