bugfix: create the right path on the remote host, not the repository identifier

diff --git a/ddm-lib b/ddm-lib
--- a/ddm-lib
+++ b/ddm-lib
@@ -35,9 +35,9 @@ function submit ()
 			path='rtorrent/torrents/'
 		;;
 	esac
-	if ! ssh $DDM_REMOTE "mkdir -p $kind"
+	if ! ssh $DDM_REMOTE "mkdir -p $path"
 	then
-		echo "could not create/verify $DDM_REMOTE:$kind"
+		echo "could not create/verify $DDM_REMOTE:$path"
 		exit 2
 	fi
 	if ssh $DDM_REMOTE "[ -e $path/$file ]"
